services:
  store:
    build:
      context: ../../../
      dockerfile: docker/local/app/Dockerfile
    ports:
      - "83:83"
    volumes:
      - ../../../.:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - taskify_nuxt_laravel

networks:
  taskify_nuxt_laravel:
    external: true